### ISSUE TITLE
Not able to play audio

### ISSUE THREAD

**Issue by fafamobile** [krystalgamer/stem-player-emulator#2] opened 2022-02-25 00:12 UTC
Audio is not able to be played when on the stem player website

**Comment by thatcherclough** [comment] 2022-02-25 00:14
You also can't download the files from the site anymore. They must've patched it

**Comment by fafamobile** [comment] 2022-02-25 00:15
> You also can't download the files from the site anymore. They must've patched it

yea they patched, need update asap

**Comment by SageSystems** [comment] 2022-02-25 00:17
same issue, more info on the error
response from stem request url `{"error":{"code":401,"error":"unauthorized","message":"JWT must be provided"}}`

**Comment by vjacksonnn** [comment] 2022-02-25 00:18
I am having the same issue unable to play audio from stemplayer website from the "play button"

**Comment by krystalgamer** [comment] 2022-02-25 00:49
Fixed it please update

**Comment by fafamobile** [comment] 2022-02-25 00:52
> Fixed it please update

Now just wont recognise the stem player when trying to connect

**Comment by thatcherclough** [comment] 2022-02-25 00:52
Same for me

**Comment by krystalgamer** [comment] 2022-02-25 00:53
they're pushing updates quick lmfao

**Comment by edinabazi** [comment] 2022-02-25 00:55
Yeah USB not getting detected since 0.4 :/

**Comment by chadhyatt** [comment] 2022-02-25 00:56
holy shit how are they patching this so quickly lol
dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man

**Comment by fafamobile** [comment] 2022-02-25 00:57
how?

**Comment by lumaaaaaa** [comment] 2022-02-25 00:57
> holy shit how are they patching this so quickly lol dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man

obfuscate an open source program? nah.

**Comment by chadhyatt** [comment] 2022-02-25 00:57
> > holy shit how are they patching this so quickly lol dude i think your best bet when updating this next is obfucating it or smth.. like dang theyre quick man
> 
> obfuscate an open source program? nah.

I mean when they're patching it within minutes...

**Comment by krystalgamer** [comment] 2022-02-25 00:57
i'd never obfuscate it

**Comment by fafamobile** [comment] 2022-02-25 00:59
how do u do that

**Comment by fafamobile** [comment] 2022-02-25 01:05
is it best to update at a later date? or are u working on something

**Comment by edinabazi** [comment] 2022-02-25 01:05
Got rid of the extra `s` in line 322 at the end and it works!

**Comment by Este-iv** [comment] 2022-02-25 01:16
Edinabazi is correct. you can remove the s and it will work.
the catch is that you can't download the album. It has been working tack by track.

**Comment by krystalgamer** [comment] 2022-02-25 01:22
fixed now
> the catch is that you can't download the album

that's by design

**Closed as completed by krystalgamer** 2022-02-25 01:22 UTC
